### ISSUE TITLE
install_mariadb.sh.j2 missing

### ISSUE THREAD

**Issue by hexmode** [LinuxCompetenceCenter/ch.l-c-c.standard-smw.packer#1]
I'm using this repo to set up a dev environment for SMW and came across a missing file.  From install_mariadb.yml:

``` yaml
- name: Place MariaDB install script
  template: src=install_mariadb.sh.j2
    dest=/root/install_mariadb.sh
    mode=700
```

**Comment by hexmode** [comment]
also missing: my.cnf.j2 from secure_mariadb.yml:

``` yaml
- name: Create file /root/.my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: mycnf_root_file.stat.exists == false
```
